package com.indiworks.capstonereality;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.view.View;
import android.widget.ImageView;

import com.bumptech.glide.Glide;

public class bheemaram extends AppCompatActivity {
    private ImageView imageView;
    ImageView  img1;
    ImageView  img2;
    ImageView  img3;
    ImageView  img4;
    ImageView  img5;
    ImageView  img6;
    ImageView  img7;
    ImageView  img8;
    ImageView  img9;
    ImageView  img10;
    ImageView  img11;
    ImageView  img12;
    ImageView  img13;
    ImageView  img14;
    ImageView  img15;
    ImageView  img16;
    ImageView  img17;
    ImageView  img18;
    ImageView  img19;
    ImageView  img20;
    ImageView  img21;
    ImageView  img22;
    ImageView  img23;
    ImageView  img24;
    ImageView  img25;
    ImageView  img26;
    ImageView  img27;
    ImageView  img28;
    ImageView  img29;
    ImageView  img30;
    ImageView  img31;
    ImageView  img32;
    ImageView  img33;
    ImageView  img34;
    ImageView  img35;
    ImageView  img36;
    ImageView  img37;
    ImageView  img38;
    ImageView  img39;
    ImageView  img40;
    ImageView  img41;
    ImageView  img42;


    String url1;
    String url2;
    String url3;
    String url4;
    String url5;
    String url6;
    String url7;
    String url8;
    String url9;
    String url10;
    String url11;
    String url12;
    String url13;
    String url14;
    String url15;
    String url16;
    String url17;
    String url18;
    String url19;
    String url20;
    String url21;
    String url22;
    String url23;
    String url24;
    String url25;
    String url26;
    String url27;
    String url28;
    String url29;
    String url30;
    String url31;
    String url32;
    String url33;
    String url34;
    String url35;
    String url36;
    String url37;
    String url38;
    String url39;
    String url40;
    String url41;
    String url42;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_bheemaram);
        imageView= (ImageView)findViewById(R.id.back);
        img1 = (ImageView)findViewById(R.id.img1);
        img2 = (ImageView)findViewById(R.id.img2);
        img3 = (ImageView)findViewById(R.id.img3);
        img4 = (ImageView)findViewById(R.id.img4);
        img5 = (ImageView)findViewById(R.id.img5);
        img6 = (ImageView)findViewById(R.id.img6);
        img7 = (ImageView)findViewById(R.id.img7);
        img8 = (ImageView)findViewById(R.id.img8);
        img9 = (ImageView)findViewById(R.id.img9);
        img10 = (ImageView)findViewById(R.id.img10);
        img11 = (ImageView)findViewById(R.id.img11);
        img12 = (ImageView)findViewById(R.id.img12);
        img13 = (ImageView)findViewById(R.id.img13);
        img14 = (ImageView)findViewById(R.id.img14);
        img15 = (ImageView)findViewById(R.id.img15);
        img16 = (ImageView)findViewById(R.id.img16);
        img17 = (ImageView)findViewById(R.id.img17);
        img18 = (ImageView)findViewById(R.id.img18);
        img19= (ImageView)findViewById(R.id.img19);
        img20 = (ImageView)findViewById(R.id.img20);
        img21 = (ImageView)findViewById(R.id.img21);
        img22 = (ImageView)findViewById(R.id.img22);
        img23 = (ImageView)findViewById(R.id.img23);
        img24 = (ImageView)findViewById(R.id.img24);
        img25 = (ImageView)findViewById(R.id.img25);
        img26 = (ImageView)findViewById(R.id.img26);
        img27 = (ImageView)findViewById(R.id.img27);
        img28 = (ImageView)findViewById(R.id.img28);
        img29 = (ImageView)findViewById(R.id.img29);
        img30 = (ImageView)findViewById(R.id.img30);
        img31 = (ImageView)findViewById(R.id.img31);
        img32 = (ImageView)findViewById(R.id.img32);
        img33 = (ImageView)findViewById(R.id.img33);
        img34 = (ImageView)findViewById(R.id.img34);
        img35 = (ImageView)findViewById(R.id.img35);
        img36 = (ImageView)findViewById(R.id.img36);
        img37 = (ImageView)findViewById(R.id.img37);
        img38 = (ImageView)findViewById(R.id.img38);
        img39 = (ImageView)findViewById(R.id.img39);
        img40 = (ImageView)findViewById(R.id.img40);
        img41 = (ImageView)findViewById(R.id.img41);
        img42 = (ImageView)findViewById(R.id.img42);




        url1	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/1.jfif"		;
        url2	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/2.jfif"		;
        url3	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/3.jfif"		;
        url4	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/4.jfif"		;
        url5	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/5.jfif"		;
        url6	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/6.jfif"		;
        url7	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/7.jfif"		;
        url8	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/8.jfif"		;
        url9	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/9.jfif"		;
        url10	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/10.jfif"		;
        url11	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/11.jpeg"		;
        url12	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/12.jfif"		;
        url13	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/13.jfif"		;
        url14	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/14.jfif"		;
        url15	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/15.jfif"		;
        url16	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/16.jfif"		;
        url17	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/17.jfif"		;
        url18	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/18.jfif"		;
        url19	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/19.jfif"		;
        url20	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/20.jfif"		;
        url21	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/21.jfif"		;
        url22	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/22.jpeg"		;
        url23	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/23.jepg"		;
        url24	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/24.jpeg"		;
        url25	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/25.jpeg"		;
        url26	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/26.jpeg"		;
        url27	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/27.jpeg"		;
        url28	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/28.jpeg"		;
        url29	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/29.jpeg"		;
        url30	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/30.jpeg"		;
        url31	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/31.jpeg"		;
        url32	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/32.jpeg"		;
        url33	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/33.jpeg"		;
        url34	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/34.jpeg"		;
        url35	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/35.jpeg"		;
        url36	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/36.jpeg"		;
        url37	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/37.jpeg"		;
        url38	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/38.jpeg"		;
        url39	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/39.jpeg"		;
        url40	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/40.jpeg"		;
        url41	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/41.jpeg"		;
        url42	 = 		"https://s3.ap-south-1.amazonaws.com/capstonereality.com/assets/db_images/shaadnagarbheemaram/42.jpeg"		;

        imageView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent intent = new Intent(bheemaram.this,projects.class);
                startActivity(intent);
            }
        });

        Glide.with(getApplicationContext()).load(Uri.parse(	url1)).into(img1);
        Glide.with(getApplicationContext()).load(Uri.parse(	url2)).into(img2);
        Glide.with(getApplicationContext()).load(Uri.parse(	url3)).into(img3);
        Glide.with(getApplicationContext()).load(Uri.parse(	url4)).into(img4);
        Glide.with(getApplicationContext()).load(Uri.parse(	url5)).into(img5);
        Glide.with(getApplicationContext()).load(Uri.parse(	url6)).into(img6);
        Glide.with(getApplicationContext()).load(Uri.parse(	url7)).into(img7);
        Glide.with(getApplicationContext()).load(Uri.parse(	url8)).into(img8);
        Glide.with(getApplicationContext()).load(Uri.parse(	url9)).into(img9);
        Glide.with(getApplicationContext()).load(Uri.parse(	url10)).into(img10);
        Glide.with(getApplicationContext()).load(Uri.parse(	url11)).into(img11);
        Glide.with(getApplicationContext()).load(Uri.parse(	url12)).into(img12);
        Glide.with(getApplicationContext()).load(Uri.parse(	url13)).into(img13);
        Glide.with(getApplicationContext()).load(Uri.parse(	url14)).into(img14);
        Glide.with(getApplicationContext()).load(Uri.parse(	url15)).into(img15);
        Glide.with(getApplicationContext()).load(Uri.parse(	url16)).into(img16);
        Glide.with(getApplicationContext()).load(Uri.parse(	url17)).into(img17);
        Glide.with(getApplicationContext()).load(Uri.parse(	url18)).into(img18);
        Glide.with(getApplicationContext()).load(Uri.parse(	url19)).into(img19);
        Glide.with(getApplicationContext()).load(Uri.parse(	url20)).into(img20);
        Glide.with(getApplicationContext()).load(Uri.parse(	url21)).into(img21);
        Glide.with(getApplicationContext()).load(Uri.parse(	url22)).into(img22);
        Glide.with(getApplicationContext()).load(Uri.parse(	url23)).into(img23);
        Glide.with(getApplicationContext()).load(Uri.parse(	url24)).into(img24);
        Glide.with(getApplicationContext()).load(Uri.parse(	url25)).into(img25);
        Glide.with(getApplicationContext()).load(Uri.parse(	url26)).into(img26);
        Glide.with(getApplicationContext()).load(Uri.parse(	url27)).into(img27);
        Glide.with(getApplicationContext()).load(Uri.parse(	url28)).into(img28);
        Glide.with(getApplicationContext()).load(Uri.parse(	url29)).into(img29);
        Glide.with(getApplicationContext()).load(Uri.parse(	url30)).into(img30);
        Glide.with(getApplicationContext()).load(Uri.parse(	url31)).into(img31);
        Glide.with(getApplicationContext()).load(Uri.parse(	url32)).into(img32);
        Glide.with(getApplicationContext()).load(Uri.parse(	url33)).into(img33);
        Glide.with(getApplicationContext()).load(Uri.parse(	url34)).into(img34);
        Glide.with(getApplicationContext()).load(Uri.parse(	url35)).into(img35);
        Glide.with(getApplicationContext()).load(Uri.parse(	url36)).into(img36);
        Glide.with(getApplicationContext()).load(Uri.parse(	url37)).into(img37);
        Glide.with(getApplicationContext()).load(Uri.parse(	url38)).into(img38);
        Glide.with(getApplicationContext()).load(Uri.parse(	url39)).into(img39);
        Glide.with(getApplicationContext()).load(Uri.parse(	url40)).into(img40);
        Glide.with(getApplicationContext()).load(Uri.parse(	url41)).into(img41);
        Glide.with(getApplicationContext()).load(Uri.parse(	url42)).into(img42);
    }
}